# Generated by Django 2.2.6 on 2019-10-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('photoid', models.IntegerField(primary_key=True, serialize=False)),
                ('photofile', models.ImageField(blank=True, db_column='photoFile', null=True, upload_to='main_app/static/main_app/img')),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('ownerid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'photos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('noofratings', models.IntegerField(blank=True, db_column='noOfRatings', null=True)),
                ('avgrating', models.FloatField(blank=True, db_column='avgRating', null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('profilephoto', models.ImageField(blank=True, db_column='profilePhoto', null=True, upload_to='main_app/static/main_app/img')),
                ('phnumber', models.CharField(blank=True, db_column='phNumber', max_length=15, null=True)),
                ('whnumber', models.CharField(blank=True, db_column='whNumber', max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rentad',
            fields=[
                ('rentid', models.IntegerField()),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main_app.Products')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('adddate', models.DateField(blank=True, db_column='addDate', null=True)),
                ('expirydate', models.DateField(blank=True, db_column='expiryDate', null=True)),
            ],
            options={
                'db_table': 'rentad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sellad',
            fields=[
                ('sellid', models.IntegerField()),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main_app.Products')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('adddate', models.DateField(blank=True, db_column='addDate', null=True)),
                ('expirydate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sellad',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Users'),
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, db_column='productName', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('photofile', models.ImageField(blank=True, db_column='photoFile', null=True, upload_to='main_app/static/main_app/img/need')),
                ('email', models.ForeignKey(blank=True, db_column='email', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Users')),
            ],
            options={
                'db_table': 'need',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Renttransaction',
            fields=[
                ('transid', models.IntegerField(db_column='transId', primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, db_column='startDate', null=True)),
                ('starttime', models.TimeField(blank=True, db_column='startTime', null=True)),
                ('enddate', models.DateField(blank=True, db_column='endDate', null=True)),
                ('endtime', models.TimeField(blank=True, db_column='endTime', null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('email', models.ForeignKey(blank=True, db_column='email', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Users')),
                ('rentid', models.ForeignKey(blank=True, db_column='rentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Rentad')),
            ],
            options={
                'db_table': 'rentTransaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wishes',
            fields=[
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main_app.Users')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Products')),
            ],
            options={
                'db_table': 'wishes',
                'managed': True,
                'unique_together': {('email', 'pid')},
            },
        ),
    ]
