# Generated by Django 2.2.6 on 2019-10-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_need_photofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
