# Generated by Django 2.2.5 on 2019-10-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191027_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renttransaction',
            name='email',
            field=models.ForeignKey(blank=True, db_column='email', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Users'),
        ),
        migrations.AlterField(
            model_name='renttransaction',
            name='rentid',
            field=models.ForeignKey(blank=True, db_column='rentid', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Rentad'),
        ),
    ]
